export const BEST_SELLING_PRODUCTS_LIMIT = 100
export const BEST_RELATED_PRODUCTS_LIMIT = 20
export const CODE_NUMBER_LENGTH = 6
export const MAX_BLOG_FEATURE = 5

export const DEFAULT_ENV = {
  APP_PORT: 9090,
  MONGO_URI: 'mongodb://localhost:27017/db',
  PASSWORD_HASH_SALT: 11,
  TOKEN_ENCRYPT_SECRET: 's3cr3t!@#',
  GRAPHQL_ENDPOINT_PATH: '/graphql',
  HEADER_TOKEN_KEY: 'access-token',
  ADMIN_TOKEN_KEY: 'admin-token',
  LOGGING_LEVEL: '1',
  TIME_LIMIT_RESOLVE_FIELD: '500',
  VERIFY_TOKEN_EXPIRES: 24, // hour
}

export const DATABASE_COLLECTION_NAME = {
  // module auth
  USER: 'users',
  NODE: 'nodes',
  NODE_TYPE: 'nodeType',
  NAVIGATION_SYSTEM: 'navigationSystems',
  PERMISSION: 'permissions',
  PROFILE: 'profiles',
  // module e-commerce -> webinfo
  CONTENT_HOME_PAGE: 'Ecom_ContentHomePage',
  CONTENT_CONTACT: 'Ecom_ContentContact',
  CONTENT_FOOTER: 'Ecom_ContentFooter',
  CONTENT_MENU: 'Ecom_ContentMenu',
  CONTENT_ABOUT_US: 'Ecom_ContentAboutUs',
  CONTENT_PURCHASE_INFO: 'Ecom_ContentPurchaseInfo',
  CONTENT_SECURITY: 'Ecom_ContentSecurity',
  VERIFY_TOKEN: 'Ecom_VerifyToken',
  ACTIVATION_TOKEN_HASH: 'Ecom_ActivationTokenHash',
  ECOMCATEGORIES: 'Ecom_Categories',
  CUSTOMERS: 'Ecom_Customers',
  DELIVERY_ADDRESSES: 'Ecom_DeliveryAddresses',
  ORDERS: 'Ecom_Orders',
  ORDERDETAILS: 'Ecom_OrderDetails',
  BLOG: 'Iitech_Blog',
  SERVICE: 'Iitech_Service',
  PAGE: 'Iitech_Page',
  MAP_SERVICE_PRODUCT: 'Iitech_MapServiceProduct',
  MAP_STOCK_MODEL_RELATED: 'Iitech_MapStockModelRelated',
  MAP_BLOG_RELATED: 'Iitech_MapBlogRelated',
  MAIL_CONTACT: 'Iitech_MailContact',
  // module sm4
  STOCK_MODELS: 'stockModels',
  STOCKS: 'stocks',
  // module his
  STAFF: 'NhanVien',
  // general
  SETTING: 'settings',
  THU_TU_SINH_MA: 'ThuTuSinhMa',
  SUBSCRIBER: 'Iitech_Subscriber',
  CONTENT_HISTORY: 'Iitech_ContentHistory',
}

export const MICROSERVICE_CLIENT = {
  HIS_SERVICE: 'HIS_SERVICE',
}

export const ROLE_TYPES = {
  APP_ROLE: 'APP_ROLE',
  CONFERENCE_ROLE: 'CONFERENCE_ROLE',
  IN_MEETING_ROLE: 'IN_MEETING_ROLE',
  GROUP_ROLE: 'GROUP_ROLE',
}

export const ROLES = {
  APP: {
    MODERATOR: 'APP_MODERATOR',
    ADMIN: 'APP_ADMIN',
    SUPERADMIN: 'APP_SUPERADMIN',
    MEMBER: 'APP_MEMBER',
    GUEST: 'APP_GUEST',
    BOT_RECORD: 'APP_BOT_RECORD',
  },
  GR: {
    MEMBER: 'GR_MEMBER',
    MODERATOR: 'GR_MODERATOR',
    ADMIN: 'GR_ADMIN',
  },
  IM: {
    OWNER: 'IM_OWNER',
    CO_HOST: 'IM_CO_HOST',
    MODERATOR: 'IM_MODERATOR',
    PARTICIPANT: 'IM_PARTICIPANT',
    CONFERENCE_GUEST: 'IM_CONFERENCE_GUEST',
    WEBINAR_GUEST: 'IM_WEBINAR_GUEST',
    TRANSLATOR: 'IM_TRANSLATOR',
  },
}

export const NODE_CATEGORY = {
  HOSPITAL: 'HOSPITAL',
  STORE: 'STORE',
  DEPARTMENT: 'DEPARTMENT',
  ROOM: 'ROOM',
}

export const NODE_TYPE = {
  EXAMINE_ROOM: 'EXAMINE_ROOM',
  HOSPITALIZE_ROOM: 'HOSPITALIZE_ROOM',
  LABORATORY_ROOM: 'LABORATORY_ROOM',
  TIPS_ROOM: 'TIPS_ROOM',
  RECEIVE_ROOM: 'RECEIVE_ROOM',
  RECOVERY_ROOM: 'RECOVERY_ROOM',
  ENDOSCOPIC_ROOM: 'ENDOSCOPIC_ROOM',
  IMAGE_ANALYSATION_ROOM: 'IMAGE_ANALYSATION_ROOM',
  SURGERY_ROOM: 'SURGERY_ROOM',
}

export const MICROSERVICE_API = {
  get_user_info: 'get_user_info',
  get_context_current_user: 'get_context_current_user',
  get_users: 'get_users',
  get_nodes: 'get_nodes',
  api_list: 'api_list',
  login: 'login',
  update_node: 'update_node',
  get_node_match_any: 'get_node_match_any',
  get_node_by_ids: 'get_node_by_ids',
}

export const TELE_API_PREFIX = 'https://api.telegram.org/bot'

type AppRoleKeys = keyof typeof ROLES.APP
export type AppRole = typeof ROLES.APP[AppRoleKeys]
type InMeetingRoleKeys = keyof typeof ROLES.IM
export type InMeetingRole = typeof ROLES.IM[InMeetingRoleKeys]
type GroupRoleKeys = keyof typeof ROLES.GR
export type GroupRole = typeof ROLES.GR[GroupRoleKeys]

// Node
type NodeCategoryKeys = keyof typeof NODE_CATEGORY
export type NodeCategory = typeof NODE_CATEGORY[NodeCategoryKeys]
type NodeTypeKeys = keyof typeof NODE_TYPE
export type NodeType = typeof NODE_TYPE[NodeTypeKeys]

export type Role = AppRole | InMeetingRoleKeys | GroupRole

const HIS_PERMISSIONS = {
  /**
   * @description
   * APP (aka Application)
   * is the permission which
   * be assign to user through roles, the permissions grant user priviledges
   * that will be examined when particular user interact with app. For example, create user.
   */
  APP: {
    GROUP_CREATE: 'APP_GROUP_CREATE',
    SETTING_UPDATE: 'APP_SETTING_UPDATE',
    REPORT_VIEW: 'APP_REPORT_VIEW',
    PROFILE_VIEW: 'APP_PROFILE_VIEW',
    RECORDING_VIEW: 'APP_RECORDING_VIEW',
    GROUP_VIEW: 'APP_GROUP_VIEW',
    ROLE_DELETE: 'APP_ROLE_DELETE',
    ROLE_EDIT: 'APP_ROLE_EDIT',
    ROLE_VIEW: 'APP_ROLE_VIEW',
    ROLE_CREATE: 'APP_ROLE_CREATE',
    USER_CREATE: 'APP_USER_CREATE',
    USER_UPDATE_ROLE: 'APP_USER_UPDATE_ROLE',
    USER_DELETE: 'APP_USER_DELETE',
    USER_EDIT: 'APP_USER_EDIT',
    USER_VIEW: 'APP_USER_VIEW',
    USER_INVITE_ROLE: 'APP_USER_INVITE_ROLE',
    MEETING_VIEW: 'APP_MEETING_VIEW',
    MEETING_CREATE: 'APP_MEETING_CREATE',
  } as const,
  /**
   * @description
   * is the permission which using in project sm3
   * to update permission data: /seeder/data/permission.ts
   */
  SM3: {
    WHOLESALE_VIEWDOCUMENT: 'WHOLESALE_VIEWDOCUMENT',
    WHOLESALE_UPDATEDOCUMENT: 'WHOLESALE_UPDATEDOCUMENT',
    WHOLESALE_UPDATEAPPROVEDDOCUMENT: 'WHOLESALE_UPDATEAPPROVEDDOCUMENT',
    WHOLESALE_PRINTREDBILL: 'WHOLESALE_PRINTREDBILL',
    WHOLESALE_DISCOUNT: 'WHOLESALE_DISCOUNT',
    WHOLESALE_CREATEDOCUMENT: 'WHOLESALE_CREATEDOCUMENT',
    WHOLESALE_CHANGESURCHARGE: 'WHOLESALE_CHANGESURCHARGE',
    WHOLESALE_CHANGEPRICE: 'WHOLESALE_CHANGEPRICE',
    WHOLESALE_CANCELDOCUMENT: 'WHOLESALE_CANCELDOCUMENT',
    WHOLESALE_CANCELAPPROVEDDOCUMENT: 'WHOLESALE_CANCELAPPROVEDDOCUMENT',
    WHOLESALE_APPROVEDOCUMENT: 'WHOLESALE_APPROVEDOCUMENT',
    WHOLESALE_ADDSTOCK: 'WHOLESALE_ADDSTOCK',
    VENDOR_VIEW: 'VENDOR_VIEW',
    VENDOR_UPDATE: 'VENDOR_UPDATE',
    VENDOR_REMOVE: 'VENDOR_REMOVE',
    VENDOR_CREATE: 'VENDOR_CREATE',
    STOREMANAGER_VIEWSTOCKNOBILL: 'STOREMANAGER_VIEWSTOCKNOBILL',
    STOREMANAGER_VIEWSALEHISTORY: 'STOREMANAGER_VIEWSALEHISTORY',
    STOREMANAGER_VIEWISNOSTOCK: 'STOREMANAGER_VIEWISNOSTOCK',
    STOREMANAGER_VIEWINVENTORYSTOCK: 'STOREMANAGER_VIEWINVENTORYSTOCK',
    STOREMANAGER_VIEWINVENTORYALLSTORE: 'STOREMANAGER_VIEWINVENTORYALLSTORE',
    STOREMANAGER_VIEWIMPORTHISTORY: 'STOREMANAGER_VIEWIMPORTHISTORY',
    STOREMANAGER_VIEWEXPORTHISTORY: 'STOREMANAGER_VIEWEXPORTHISTORY',
    STOREMANAGER_VIEWCOSTINVENTORYSTOCK: 'STOREMANAGER_VIEWCOSTINVENTORYSTOCK',
    STOREIMPORT_VIEWDOCUMENT: 'STOREIMPORT_VIEWDOCUMENT',
    STOREIMPORT_UPDATESTOCKMODEL: 'STOREIMPORT_UPDATESTOCKMODEL',
    STOREIMPORT_UPDATEDOCUMENT: 'STOREIMPORT_UPDATEDOCUMENT',
    STOREIMPORT_UPDATEAPPROVEDDOCUMENT: 'STOREIMPORT_UPDATEAPPROVEDDOCUMENT',
    STOREIMPORT_CREATEDOCUMENT: 'STOREIMPORT_CREATEDOCUMENT',
    STOREIMPORT_CANCELDOCUMENT: 'STOREIMPORT_CANCELDOCUMENT',
    STOREIMPORT_CANCELAPPROVEDDOCUMENT: 'STOREIMPORT_CANCELAPPROVEDDOCUMENT',
    STOREIMPORT_APPROVEDOCUMENT: 'STOREIMPORT_APPROVEDOCUMENT',
    STOREIMPORT_ADDSTOCK: 'STOREIMPORT_ADDSTOCK',
    STOREEXPORT_VIEW: 'STOREEXPORT_VIEW',
    STOREEXPORT_UPDATEDOCUMENT: 'STOREEXPORT_UPDATEDOCUMENT',
    STOREEXPORT_IMPORTVERIFIED: 'STOREEXPORT_IMPORTVERIFIED',
    STOREEXPORT_EXPORTVERIFIED: 'STOREEXPORT_EXPORTVERIFIED',
    STOREEXPORT_DELETESTOCK: 'STOREEXPORT_DELETESTOCK',
    STOREEXPORT_CREATE: 'STOREEXPORT_CREATE',
    STOREEXPORT_CANCELEXPORT: 'STOREEXPORT_CANCELEXPORT',
    STOREEXPORT_CANCELDOCUMENT: 'STOREEXPORT_CANCELDOCUMENT',
    STOREEXPORT_ADDSTOCK: 'STOREEXPORT_ADDSTOCK',
    STOCKWARNING_ORDER: 'STOCKWARNING_ORDER',
    STOCKWARNING_EDIT: 'STOCKWARNING_EDIT',
    STOCKWARNING_CREATEEXPORTDOCUMENT: 'STOCKWARNING_CREATEEXPORTDOCUMENT',
    STOCKMODEL_VIEWHISTORY: 'STOCKMODEL_VIEWHISTORY',
    STOCKMODEL_VIEWCOSTBYSTORE: 'STOCKMODEL_VIEWCOSTBYSTORE',
    STOCKMODEL_VIEW: 'STOCKMODEL_VIEW',
    STOCKMODEL_UPDATE: 'STOCKMODEL_UPDATE',
    STOCKMODEL_REMOVE: 'STOCKMODEL_REMOVE',
    STOCKMODEL_EDITSALEPRICE: 'STOCKMODEL_EDITSALEPRICE',
    STOCKMODEL_CREATE: 'STOCKMODEL_CREATE',
    STOCKMODELORDER_VIEW: 'STOCKMODELORDER_VIEW',
    STOCKMODELORDER_CREATE: 'STOCKMODELORDER_CREATE',
    STOCKMODELORDERREPORT_VIEWDETAIL: 'STOCKMODELORDERREPORT_VIEWDETAIL',
    STOCKMODELORDERREPORT_VIEW: 'STOCKMODELORDERREPORT_VIEW',
    STOCKMODELORDERREPORT_VERIFY: 'STOCKMODELORDERREPORT_VERIFY',
    STOCKMODELORDERREPORT_PRINT: 'STOCKMODELORDERREPORT_PRINT',
    STOCKMODELORDERREPORT_EXPORTEXCEL: 'STOCKMODELORDERREPORT_EXPORTEXCEL',
    STOCKMODELORDERREPORT_DELETE: 'STOCKMODELORDERREPORT_DELETE',
    STOCKCONTROL_VIEWDOCUMENT: 'STOCKCONTROL_VIEWDOCUMENT',
    STOCKCONTROL_UPDATEDOCUMENT: 'STOCKCONTROL_UPDATEDOCUMENT',
    STOCKCONTROL_CREATEDOCUMENT: 'STOCKCONTROL_CREATEDOCUMENT',
    STOCKCONTROL_CHECKINVENTORY: 'STOCKCONTROL_CHECKINVENTORY',
    STOCKCONTROL_CANCELDOCUMENT: 'STOCKCONTROL_CANCELDOCUMENT',
    STOCKCONTROL_CANCELAPPROVESTOCK: 'STOCKCONTROL_CANCELAPPROVESTOCK',
    STOCKCONTROL_APPROVESTOCK: 'STOCKCONTROL_APPROVESTOCK',
    STOCKCONTROL_APPROVEDOCUMENT: 'STOCKCONTROL_APPROVEDOCUMENT',
    STOCKCONTROL_ADDSTOCK: 'STOCKCONTROL_ADDSTOCK',
    SETTING_UPDATEMUNE: 'SETTING_UPDATEMUNE',
    SETTING_UPDATE: 'SETTING_UPDATE',
    SETTING_ADVANCE: 'SETTING_ADVANCE',
    RETURNRETAIL_DOCUMENTVIEWDOCUMENT: 'RETURNRETAIL_DOCUMENTVIEWDOCUMENT',
    RETURNRETAIL_DOCUMENTVIEWDETAIL: 'RETURNRETAIL_DOCUMENTVIEWDETAIL',
    RETURNRETAIL_DOCUMENTVERIFYDOCUMENT: 'RETURNRETAIL_DOCUMENTVERIFYDOCUMENT',
    RETURNRETAIL_DOCUMENTREMOVEDOCUMENT: 'RETURNRETAIL_DOCUMENTREMOVEDOCUMENT',
    RETURNRETAIL_DOCUMENTCREATEDOCUMENT: 'RETURNRETAIL_DOCUMENTCREATEDOCUMENT',
    RETURNRETAIL_DOCUMENTADDSTOCK: 'RETURNRETAIL_DOCUMENTADDSTOCK',
    RETURNRETAIL_CREATE: 'RETURNRETAIL_CREATE',
    RETURNRETAIL_CHANGEPENATY: 'RETURNRETAIL_CHANGEPENATY',
    RETURNRETAIL_APPROVE: 'RETURNRETAIL_APPROVE',
    RETAIL_VIEWDOCUMENT: 'RETAIL_VIEWDOCUMENT',
    RETAIL_UPDATEDOCUMENT: 'RETAIL_UPDATEDOCUMENT',
    RETAIL_PAYMENT: 'RETAIL_PAYMENT',
    RETAIL_NOLIMMITEDDISCOUNT: 'RETAIL_NOLIMMITEDDISCOUNT',
    RETAIL_DISCOUNT: 'RETAIL_DISCOUNT',
    RETAIL_DEBIT: 'RETAIL_DEBIT',
    RETAIL_CREATEDOCUMENT: 'RETAIL_CREATEDOCUMENT',
    RETAIL_CHANGESURCHARE: 'RETAIL_CHANGESURCHARE',
    RETAIL_CHANGEPRICE: 'RETAIL_CHANGEPRICE',
    RETAIL_CANCELDOCUMENT: 'RETAIL_CANCELDOCUMENT',
    RETAIL_ADDSTOCK: 'RETAIL_ADDSTOCK',
    RETAILDOCUMENT_VIEWTOTAL: 'RETAILDOCUMENT_VIEWTOTAL',
    RETAILDOCUMENT_VIEWPROFIT: 'RETAILDOCUMENT_VIEWPROFIT',
    RETAILDOCUMENT_VIEWDOCUMENT: 'RETAILDOCUMENT_VIEWDOCUMENT',
    REPORT_VIEW: 'REPORT_VIEW',
    PURCHASEORDER_VIEWDOCUMENT: 'PURCHASEORDER_VIEWDOCUMENT',
    PURCHASEORDER_UPDATESTOCKMODEL: 'PURCHASEORDER_UPDATESTOCKMODEL',
    PURCHASEORDER_UPDATEDOCUMENT: 'PURCHASEORDER_UPDATEDOCUMENT',
    PURCHASEORDER_CREATEDOCUMENT: 'PURCHASEORDER_CREATEDOCUMENT',
    PURCHASEORDER_CANCELDOCUMENT: 'PURCHASEORDER_CANCELDOCUMENT',
    PURCHASEORDER_APPROVEDOCUMENT: 'PURCHASEORDER_APPROVEDOCUMENT',
    PURCHASEORDER_ADDSTOCK: 'PURCHASEORDER_ADDSTOCK',
    PAYSLIP_VIEWTHEIROWNPAYSLIPS: 'PAYSLIP_VIEWTHEIROWNPAYSLIPS',
    PAYSLIP_VIEWALLPAYSLIPS: 'PAYSLIP_VIEWALLPAYSLIPS',
    PAYSLIP_UPDATEPAYSLIP: 'PAYSLIP_UPDATEPAYSLIP',
    PAYDEBT_VIEWDEBT: 'PAYDEBT_VIEWDEBT',
    PAYDEBT_DEBTSETTLEMENT: 'PAYDEBT_DEBTSETTLEMENT',
    PATIENT_VIEW: 'PATIENT_VIEW',
    PATIENT_UPDATE: 'PATIENT_UPDATE',
    PATIENT_REMOVE: 'PATIENT_REMOVE',
    PATIENT_CREATE: 'PATIENT_CREATE',
    EXPORT_NOTEXCEL: 'EXPORT_NOTEXCEL',
    EXPORT_ACCOUNTING: 'EXPORT_ACCOUNTING',
    EXAMINATIONSESSION_VIEWDOCUMENT: 'EXAMINATIONSESSION_VIEWDOCUMENT',
    EXAMINATIONSESSION_UPDATEDOCUMENT: 'EXAMINATIONSESSION_UPDATEDOCUMENT',
    EXAMINATIONSESSION_PRINTRESULT: 'EXAMINATIONSESSION_PRINTRESULT',
    EXAMINATIONSESSION_PRINTPRESCRIPTION:
      'EXAMINATIONSESSION_PRINTPRESCRIPTION',
    EXAMINATIONSESSION_CREATEDDOCUMENT: 'EXAMINATIONSESSION_CREATEDDOCUMENT',
    EXAMINATIONSESSION_CANCELDOCUMENT: 'EXAMINATIONSESSION_CANCELDOCUMENT',
    EXAMINATIONSESSION_APPROVEDOCUMENT: 'EXAMINATIONSESSION_APPROVEDOCUMENT',
    DOCTOR_VIEW: 'DOCTOR_VIEW',
    DOCTOR_UPDATE: 'DOCTOR_UPDATE',
    DOCTOR_REMOVE: 'DOCTOR_REMOVE',
    DOCTOR_CREATE: 'DOCTOR_CREATE',
    DIRECTORY_VIEW: 'DIRECTORY_VIEW',
    DIRECTORY_EDIT: 'DIRECTORY_EDIT',
    DIRECTORY_DELETE: 'DIRECTORY_DELETE',
    DIRECTORY_CREATE: 'DIRECTORY_CREATE',
    CUSTOMER_VIEW: 'CUSTOMER_VIEW',
    CUSTOMER_UPDATE: 'CUSTOMER_UPDATE',
    CUSTOMER_REMOVE: 'CUSTOMER_REMOVE',
    CUSTOMER_CREATE: 'CUSTOMER_CREATE',
    CONNECTNATIONAL_VIEWDOCUMENT: 'CONNECTNATIONAL_VIEWDOCUMENT',
    CONNECTNATIONAL_UPDATEINFO: 'CONNECTNATIONAL_UPDATEINFO',
    CONNECTNATIONAL_CREATEVITURALBILL: 'CONNECTNATIONAL_CREATEVITURALBILL',
    CONNECTNATIONAL_CANCEL: 'CONNECTNATIONAL_CANCEL',
    CONNECTNATIONAL_APPROVE: 'CONNECTNATIONAL_APPROVE',
    CASHMANAGEMENT_VIEWCASH: 'CASHMANAGEMENT_VIEWCASH',
    CASHMANAGEMENT_CREATERECEIPTS: 'CASHMANAGEMENT_CREATERECEIPTS',
    CASHMANAGEMENT_CREATEPAYMENTSLIP: 'CASHMANAGEMENT_CREATEPAYMENTSLIP',
    CASHMANAGEMENT_ADDFIRSTDAYCASH: 'CASHMANAGEMENT_ADDFIRSTDAYCASH',
    APPOINTMENT_VIEWDOCUMENT: 'APPOINTMENT_VIEWDOCUMENT',
    APPOINTMENT_VIEWALLDOCUMENT: 'APPOINTMENT_VIEWALLDOCUMENT',
    APPOINTMENT_UPDATEDOCUMENT: 'APPOINTMENT_UPDATEDOCUMENT',
    APPOINTMENT_PRINTDOCUMENT: 'APPOINTMENT_PRINTDOCUMENT',
    APPOINTMENT_CREATEDDOCUMENT: 'APPOINTMENT_CREATEDDOCUMENT',
    APPOINTMENT_CANCELDOCUMENT: 'APPOINTMENT_CANCELDOCUMENT',
    APPOINTMENT_APPROVEDOCUMENT: 'APPOINTMENT_APPROVEDOCUMENT',
    VIENPHI_CREATE_BIENLAI: 'VIENPHI_CREATE_BIENLAI',
    VIENPHI_UPDATE_BIENLAI: 'VIENPHI_UPDATE_BIENLAI',
    VIENPHI_DELETE_BIENLAI: 'VIENPHI_DELETE_BIENLAI',
    VIENPHI_CANCEL_HACHTOAN: 'VIENPHI_CANCEL_HACHTOAN',
    VIENPHI_DELETE_BIENLAI_THANHTOAN: 'VIENPHI_DELETE_BIENLAI_THANHTOAN',
    // admin
    ADMIN: 'ADMIN',
  } as const,
  CLINIC: {
    CLINIC_REPORT_VIEW_ALL_PAYMENT_RECEIPT:
      'CLINIC_REPORT_VIEW_ALL_PAYMENT_RECEIPT',
    CLINIC_EXAMINATION_VIEW: 'CLINIC_EXAMINATION_VIEW',
    CLINIC_STOREEXPORT_VIEW: 'CLINIC_STOREEXPORT_VIEW',
    CLINIC_SUPPLY_DRUG_CANCEL: 'CLINIC_SUPPLY_DRUG_CANCEL',
    CLINIC_ASSIGN_SUBCLINICAL_VIEW: 'CLINIC_ASSIGN_SUBCLINICAL_VIEW',
    CLINIC_REPORT_VIEW_RECEIPT_LIST: 'CLINIC_REPORT_VIEW_RECEIPT_LIST',
    CLINIC_REPORT_VIEW: 'CLINIC_REPORT_VIEW',
    CLINIC_DEPOSIT_REQUEST_LIST_VIEW: 'CLINIC_DEPOSIT_REQUEST_LIST_VIEW',
    CLINIC_DAILY_COLLECTION_REPORT_VIEW: 'CLINIC_DAILY_COLLECTION_REPORT_VIEW',
    CLINIC_DIRECTORY_EDIT: 'CLINIC_DIRECTORY_EDIT',
    CLINIC_IMAGE_ANALYSATION_CANCEL: 'CLINIC_IMAGE_ANALYSATION_CANCEL',
    CLINIC_MEDICAL_TEST_APPROVE: 'CLINIC_MEDICAL_TEST_APPROVE',
    CLINIC_STOREEXPORT_CREATE: 'CLINIC_STOREEXPORT_CREATE',
    CLINIC_STOREIMPORT_VIEWDOCUMENT: 'CLINIC_STOREIMPORT_VIEWDOCUMENT',
    CLINIC_EXAMINATION_CANCEL: 'CLINIC_EXAMINATION_CANCEL',
    CLINIC_IMAGE_ANALYSATION_CHECK_UP: 'CLINIC_IMAGE_ANALYSATION_CHECK_UP',
    CLINIC_STOREIMPORT_UPDATEAPPROVEDDOCUMENT:
      'CLINIC_STOREIMPORT_UPDATEAPPROVEDDOCUMENT',
    CLINIC_EXAMINATION_APPROVE: 'CLINIC_EXAMINATION_APPROVE',
    CLINIC_STOCKMODEL_UPDATE: 'CLINIC_STOCKMODEL_UPDATE',
    CLINIC_STOCKMODEL_CREATE: 'CLINIC_STOCKMODEL_CREATE',
    CLINIC_MEDICAL_TEST_CREATE: 'CLINIC_MEDICAL_TEST_CREATE',
    CLINIC_IMAGE_ANALYSATION_APPROVE: 'CLINIC_IMAGE_ANALYSATION_APPROVE',
    CLINIC_STOREIMPORT_CANCELAPPROVEDDOCUMENT:
      'CLINIC_STOREIMPORT_CANCELAPPROVEDDOCUMENT',
    CLINIC_STOREEXPORT_CANCELEXPORT: 'CLINIC_STOREEXPORT_CANCELEXPORT',
    CLINIC_DIRECTORY_VIEW: 'CLINIC_DIRECTORY_VIEW',
    CLINIC_EXAMINATION_CHECK_UP: 'CLINIC_EXAMINATION_CHECK_UP',
    CLINIC_STOREEXPORT_CANCELDOCUMENT: 'CLINIC_STOREEXPORT_CANCELDOCUMENT',
    CLINIC_STOREEXPORT_ADDSTOCK: 'CLINIC_STOREEXPORT_ADDSTOCK',
    CLINIC_STOREEXPORT_IMPORTVERIFIED: 'CLINIC_STOREEXPORT_IMPORTVERIFIED',
    CLINIC_STOCKMODEL_REMOVE: 'CLINIC_STOCKMODEL_REMOVE',
    CLINIC_CASH_DESK_CREATE: 'CLINIC_CASH_DESK_CREATE',
    CLINIC_DIRECTORY_CREATE: 'CLINIC_DIRECTORY_CREATE',
    CLINIC_STOCKMODEL_VIEWHISTORY: 'CLINIC_STOCKMODEL_VIEWHISTORY',
    CLINIC_DIRECTORY_DELETE: 'CLINIC_DIRECTORY_DELETE',
    CLINIC_CASH_DESK_EDIT: 'CLINIC_CASH_DESK_EDIT',
    CLINIC_STOREIMPORT_UPDATESTOCKMODEL: 'CLINIC_STOREIMPORT_UPDATESTOCKMODEL',
    CLINIC_MEDICAL_TEST_CANCEL: 'CLINIC_MEDICAL_TEST_CANCEL',
    CLINIC_IMAGE_ANALYSATION_VIEW: 'CLINIC_IMAGE_ANALYSATION_VIEW',
    CLINIC_STOREIMPORT_CREATEDOCUMENT: 'CLINIC_STOREIMPORT_CREATEDOCUMENT',
    CLINIC_SUPPLY_DRUG_APPROVE: 'CLINIC_SUPPLY_DRUG_APPROVE',
    CLINIC_MEDICAL_TEST_EDIT: 'CLINIC_MEDICAL_TEST_EDIT',
    CLINIC_STOCKMODEL_VIEWCOSTBYSTORE: 'CLINIC_STOCKMODEL_VIEWCOSTBYSTORE',
    CLINIC_IMAGE_ANALYSATION_CHOOSE_TEST:
      'CLINIC_IMAGE_ANALYSATION_CHOOSE_TEST',
    CLINIC_CASH_DESK_VIEW: 'CLINIC_CASH_DESK_VIEW',
    CLINIC_IMAGE_ANALYSATION_EDIT: 'CLINIC_IMAGE_ANALYSATION_EDIT',
    CLINIC_IMAGE_ANALYSATION_CREATE: 'CLINIC_IMAGE_ANALYSATION_CREATE',
    CLINIC_RECEIVE_CANCEL: 'CLINIC_RECEIVE_CANCEL',
    CLINIC_RECEIVE_EDIT: 'CLINIC_RECEIVE_EDIT',
    CLINIC_STOREIMPORT_UPDATEDOCUMENT: 'CLINIC_STOREIMPORT_UPDATEDOCUMENT',
    CLINIC_STOREEXPORT_DELETESTOCK: 'CLINIC_STOREEXPORT_DELETESTOCK',
    CLINIC_STOCKMODEL_VIEW: 'CLINIC_STOCKMODEL_VIEW',
    CLINIC_MEDICAL_TEST_CHECK_UP: 'CLINIC_MEDICAL_TEST_CHECK_UP',
    CLINIC_STOREIMPORT_CANCELDOCUMENT: 'CLINIC_STOREIMPORT_CANCELDOCUMENT',
    CLINIC_MEDICAL_TEST_CHOOSE_TEST: 'CLINIC_MEDICAL_TEST_CHOOSE_TEST',
    CLINIC_MEDICAL_TEST_VIEW: 'CLINIC_MEDICAL_TEST_VIEW',
    CLINIC_CASH_DESK_REFUND: 'CLINIC_CASH_DESK_REFUND',
    CLINIC_STOCKMODEL_EDITSALEPRICE: 'CLINIC_STOCKMODEL_EDITSALEPRICE',
    CLINIC_STOREIMPORT_ADDSTOCK: 'CLINIC_STOREIMPORT_ADDSTOCK',
    CLINIC_RECEIVE_CREATE: 'CLINIC_RECEIVE_CREATE',
    CLINIC_RECEIVE_VIEW: 'CLINIC_RECEIVE_VIEW',
    CLINIC_STOREEXPORT_EXPORTVERIFIED: 'CLINIC_STOREEXPORT_EXPORTVERIFIED',
    CLINIC_STOREIMPORT_APPROVEDOCUMENT: 'CLINIC_STOREIMPORT_APPROVEDOCUMENT',
    CLINIC_SUPPLY_DRUG_VIEW: 'CLINIC_SUPPLY_DRUG_VIEW',
    CLINIC_ADMIN: 'CLINIC_ADMIN',
  } as const,
}

export const PERMISSIONS = [
  HIS_PERMISSIONS.APP,
  HIS_PERMISSIONS.SM3,
  HIS_PERMISSIONS.CLINIC,
].reduce((permissionIds, currentElement) => {
  permissionIds.push(...Object.values(currentElement))
  return permissionIds
}, [])

type AppPermissionKeys = keyof typeof HIS_PERMISSIONS.APP
export type AppPermission = typeof HIS_PERMISSIONS.APP[AppPermissionKeys]

type SM3PermissionKeys = keyof typeof HIS_PERMISSIONS.SM3
export type SM3Permission = typeof HIS_PERMISSIONS.SM3[SM3PermissionKeys]

type ClinicPermissionKeys = keyof typeof HIS_PERMISSIONS.CLINIC
export type ClinicPermission =
  typeof HIS_PERMISSIONS.CLINIC[ClinicPermissionKeys]

export type Permission = AppPermission | SM3Permission | ClinicPermission
